### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by njian0** [Neikon/Fox11#11]

**Comment by Neikon** [comment]
do you still need help?
![imagen](https://github.com/Neikon/Fox11/assets/1765319/6eaa8bba-56d7-4cab-99d7-eab7c429b30a)

**Comment by njian0** [comment]
Yes...
But I'm not sure if you can help haha😅

**Comment by njian0** [comment]
Yeah...😅

It just doesn't appear on my Firefox. This looks really nice and just wanted to try it.

I'm just wondering if it's in the right place? Had to make the file myself because "chrome" wasn't there.
Or maybe a component is missing.

I also have some extensions.
Momentum: [https://addons.mozilla.org/en-US/firefox/addon/momentumdash/](url)
AdGuard AdBlocker: [https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/](url)

![image](https://github.com/Neikon/Fox11/assets/167185483/f6eb12ae-f456-4cc3-a826-91cb687dfd75)
![image](https://github.com/Neikon/Fox11/assets/167185483/c854c8ff-b4fc-4ceb-b2b6-0a3811b3b099)
![image](https://github.com/Neikon/Fox11/assets/167185483/625deaa9-1b93-4a15-afda-766b3914c5df)
![image](https://github.com/Neikon/Fox11/assets/167185483/dc8ab550-1e9a-4df8-af8e-c8538cf62bd7)

**Comment by Neikon** [comment]
There is a folder that you don't need. The path should be 
"firefoxProfileXxXXXXX/chrome/userchrome.css"  (and the other files and folders)

and not "firefoxProfileXxXXXXX/chrome/~~fox11~~/userchrome.css"

these files/imagen are of a different theme but they are useful to show you the path
![imagen](https://github.com/Neikon/Fox11/assets/1765319/7374546c-7d4d-4e46-b4b4-5ff3f3b7c2f9)

**Comment by njian0** [comment]
Okay, I'll give that a try.

It worked, thanks!
