### ISSUE TITLE
[Question] Tab thingy

### ISSUE THREAD

**Issue by njian0** [Neikon/Fox11#12]
Hi again! (Ignore the timeline)

I was wondering what you did to make that tab thing? Like the colored lines at the top of the pinned tabs and the FireFox logo?
![image](https://github.com/Neikon/Fox11/assets/167185483/2fa2a857-3cc0-41dd-ae99-265b315eb394)

Thanks!

**Comment by Neikon** [comment]
These are simple pin tabs in containers. rght click in a tab >> pin

**Comment by njian0** [comment]
Oh yeah I know how to pin a tab😅

I was just wondering about where you got the Firefox logo and why are there colored lines on top of the pinned tabs
Is it an extension or something like that?
![image](https://github.com/Neikon/Fox11/assets/167185483/21b416ac-30f7-42e3-a53a-06cb1682a13e)

**Comment by Neikon** [comment]
Lines are containers indicators https://addons.mozilla.org/es/firefox/addon/multi-account-containers/
Firefox logo is "firefox view" a default button of firefox but I think know has other icon like this 
![imagen](https://github.com/Neikon/Fox11/assets/1765319/0e85ef21-a0a5-4beb-a3b7-618a7cd9883c)

**Comment by njian0** [comment]
Alright, thanks!
