### ISSUE TITLE
Toolbar buttons are not clear

### ISSUE THREAD

**Issue by ltfred** [Neikon/Fox11#3]
Thank you for sharing, but I have a problem with it, toolbar buttons are not clear when the header is black.

![图片](https://github.com/Neikon/Fox11/assets/51397257/919acaa8-9517-48da-a2c2-98aef68752a3)

![图片](https://github.com/Neikon/Fox11/assets/51397257/362ee969-62aa-421c-9b8f-ab078f079dc6)

![图片](https://github.com/Neikon/Fox11/assets/51397257/37c35e4d-4801-4c96-823e-4580ecff2021)

**Comment by Neikon** [comment]
Do you download this release https://github.com/Neikon/Fox11/releases/tag/v1.0 ?

On the other hand, I am attaching the version I am using right now in case you want to try it and tell me if it fixes your bug.

Tomorrow I will check it in more depth to see if I need to release a new version.
[chrome.zip](https://github.com/Neikon/Fox11/files/12384043/chrome.zip)

**Comment by ltfred** [comment]
Thanks, I logged out of firefox completely and restarted it, the toolbar is clear.
