### ISSUE TITLE
randomly breaks

### ISSUE THREAD

**Issue by powerdollkirby** [Neikon/Fox11#5]
i have mfe disabled. idk why it keeps breaking like this, after that i have to do task manager to close it and restart
![image](https://github.com/Neikon/Fox11/assets/105698999/3e633a48-7b01-4234-9ec8-f667d234baed)

**Comment by Neikon** [comment]
What add-ons do you have?
I've been having the firefox interface break for several months now and I can't find the cause. It has been happening to me since before I created this theme and used MFE. My brother uses my theme and the addons that he uses I also have (although I have some more than him) and he does not crashes.

regardless of this error, if you do not want to use MFE, comment the corresponding in userchrome.css and it will not matter the configuration you have in MFE that will not be used. or you can not have any rule in MFE for Firefox and it will not be used either. But the 1st option is preferable.

**Comment by powerdollkirby** [comment]
well i don't know then :c 
![image](https://github.com/Neikon/Fox11/assets/105698999/f916a678-ad44-47f7-bc56-230fd3f6cc19)
i have scripts for youtube like for padding and stuff but it breaks with certain sites with js or something, i noticed when something like a popup or whenever i click something on any site that will cause the interface to break like that, it works perfectly on youtube/instagram and more social media, i dont think the automatic dark mode will cause the interface to break like that, havent tried it on linux to see if it breaks too
i dont have mfe running and it breaks too, this happens before and after the last release with mica by default, but i dont really care about the transparency tho

**Comment by Neikon** [comment]
don't you have vivaldifox or adaptative tab bar color?
I'm going to try to remove plugins/theme to see who causes the crashes but in principle it's not the theme thing
My first suspect is vivaldifox

P.D: why ghostery and not ublock origin? just curious

**Comment by powerdollkirby** [comment]
> don't you have vivaldifox or adaptative tab bar color?
> 
> I'm going to try to remove plugins/theme to see who causes the crashes but in principle it's not the theme thing
> 
> My first suspect is vivaldifox
> 
> 
> 
> P.D: why ghostery and not ublock origin? just curious

Nope nothing related to that, I installed Firefox color recently but the interface broke before that
If you find a solution or what exactly breaks it, let me know:(

I used to use ublock origin, I changed to ghostery like a month ago because it works better on YouTube in my experience, sometimes with uBlock the ads still load, I feel it's slower when loading sites
And it's open source since 2018

**Comment by Neikon** [comment]
Don't worry, I will write in this issue when I find the solution or the cause of the problems.
I will try to disable/enable things until I find the cause.

I never see a youtube add but it's nice to know that there is a good alternative to ublock origin.

**Comment by Neikon** [comment]
do you notice if UI crash when you change from a light to dark web or dark to light web?

**Comment by powerdollkirby** [comment]
not really, even if i reload a random tab github for example, and theres something playing in the back sometimes it crashes the players, for example the twitch player crashes (pop-up too)


also how can i make it thinner?
![image](https://github.com/Neikon/Fox11/assets/105698999/c89a3eaa-f62b-4cef-ad6d-b3d25e247ef8)

(waterfox right side)

**Comment by Neikon** [comment]
do you have reports in about:crashes ? if you have, send it all and them share any one with me pls.
i want to know if you have this kind of crashes like me https://crash-stats.mozilla.org/report/index/955a477f-4113-4681-ac11-11d250230828

**Comment by powerdollkirby** [comment]
i checked it and it doesnt show as a crash i think idk, but the last firefox update broke it completely, i breaks the entire thing, i cant click anything, cant minimize, maximize or close not even scroll tru tabs, it goes super super tiny sometimes
![Recording 2023-08-30 021500](https://github.com/Neikon/Fox11/assets/105698999/ff3b8809-14da-4ca5-a70d-15a7db784178)

**Comment by Neikon** [comment]
> i checked it and it doesnt show as a crash i think idk, but the last firefox update broke it completely, i breaks the entire thing, i cant click anything, cant minimize, maximize or close not even scroll tru tabs, it goes super super tiny sometimes ![Recording 2023-08-30 021500](https://user-images.githubusercontent.com/105698999/264295671-ff3b8809-14da-4ca5-a70d-15a7db784178.gif)

new theme version was released yesterday to support Firefox 117 and fix all that.
But Firefox 117 deprecate transparencies in windows.

**Comment by powerdollkirby** [comment]
> > i checked it and it doesnt show as a crash i think idk, but the last firefox update broke it completely, i breaks the entire thing, i cant click anything, cant minimize, maximize or close not even scroll tru tabs, it goes super super tiny sometimes ![Recording 2023-08-30 021500](https://user-images.githubusercontent.com/105698999/264295671-ff3b8809-14da-4ca5-a70d-15a7db784178.gif)
> >       
> >         [
> >           
> >             ![Recording 2023-08-30 021500](https://user-images.githubusercontent.com/105698999/264295671-ff3b8809-14da-4ca5-a70d-15a7db784178.gif)
> >           
> >         ](https://user-images.githubusercontent.com/105698999/264295671-ff3b8809-14da-4ca5-a70d-15a7db784178.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/105698999/264295671-ff3b8809-14da-4ca5-a70d-15a7db784178.gif)
> 
> new theme version was released yesterday to support Firefox 117 and fix all that. But Firefox 117 deprecate transparencies in windows.

So no transparency anymore? I didn’t read the release notes

**Comment by Neikon** [comment]
> So no transparency anymore? I didn’t read the release notes

in windows &  firefox 117, no. To get transparencies in win to you need firefox 115 ESR
in linux all should work as always.

**Comment by powerdollkirby** [comment]
gg then
