### ISSUE TITLE
Tab bar is bright white on browser startup 

### ISSUE THREAD

**Issue by Hazem42** [Neikon/Fox11#8]
How can I change it? the background is fine, only the tab bar is white.
Arch Linux
Gnome 45

**Comment by Neikon** [comment]
Do you use Vivaldifox or Adaptive color add-on?
Your default Firefox theme is light or dark?
Your system theme is light or dark?

I'm asking all this because I think the problem is your default settings is light, and tab bar is light until Vivaldifox o Adaptive color works

**Comment by Hazem42** [comment]
System theme is dark
browser theme is auto (should I change it to dark?)
I use adaptive color add-on

Edit: switching from auto to dark fixed it thank you <3

**Comment by Hazem42** [comment]
Unrelated question
How can I change the main background color?

**Comment by Neikon** [comment]
By background color do you mean the color of the interface in general or the background of the new tab?
If it is the first one, the simplest way would be to install a theme from the Firefox store with the color you want, if you want a fixed color.

If it is the second one, adding a few lines of CSS code to userchrome.css, but I don't know the exact code to do it.
